### ISSUE TITLE
Name clashes with http://www.ratpack.io

### ISSUE THREAD

**Issue by ldaley** [timfel/ratpack#1]
Hi,

I'm the lead of http://www.ratpack.io/. Just wanted to let you know that this name clash exists.

This isn't a cease-and-desist type thing; just letting you know.

**Comment by timfel** [comment]
Seems that idea was too obvious ;) I heard from a couple of other "inspired by Sinatra" things that considered or had RatPack as a name, too, back when I created my library. I doubt sometime will confuse a Smalltalk implementation with Groovy...

Thanks for letting me know, and good luck with your endeavors
